name: "Treffynnon's PowerShell scripting utilities"
on: [push, pull_request]

jobs:
  lint:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PSScriptAnalyzer
      run: Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck
    - name: Invoke linter
      run: Invoke-ScriptAnalyzer -Path .\TrUtilities\
    - name: Build manifest
      run: .\TrUtilities\generateManifest.ps1
    - name: Lint manifest
      run: Test-ModuleManifest -Path .\TrUtilities\TrUtilities.psd1
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck
    - name: Invoke tests
      run: Invoke-Pester .\TrUtilities\
