name: "Treffynnon's PowerShell scripting utilities"
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build manifest
      run: |
        $Tag = ${Env:GITHUB_REF} -Replace "refs/tags/",""
        .\TrUtilities\generateManifest.ps1 -ModuleVersion $Tag
    - name: Lint manifest
      run: Test-ModuleManifest -Path .\TrUtilities\TrUtilities.psd1
    - name: Publish Module
      run: Publish-Module -Path ".\TrUtilities" -NuGetApiKey "${{ secrets.POWERSHELL_GALLERY_KEY }}" -Confirm -ErrorAction Stop -Force
