name: "Treffynnon's PowerShell scripting utilities"
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.POWERSHELL_GALLERY_KEY }}
        nuget-version: '5.1.0'
    - name: Build manifest
      run: .\TrUtilities\generateManifest.ps1 -ModuleVersion "${{ github.event.release.tag_name }}"
    - name: Lint manifest
      run: Test-ModuleManifest -Path ".\TrUtilities\TrUtilities.psd1"
    - name: Publish Module
      run: |
        Write-Host "Publishing version ${{ github.event.release.tag_name }}"
        Publish-Module -Path ".\TrUtilities" -NuGetApiKey "${{ secrets.POWERSHELL_GALLERY_KEY }}" -Confirm -ErrorAction Stop -Force -Debug
